name: Create or Update PR

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

    secrets:
      PAT:
        required: true

jobs:
  createOrUpdatePR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ inputs.branch }}
          destination_branch: 'main'
          pr_title: ${{ inputs.branch }}
          pr_body: |
            *Please review before merging.*

          pr_label: 'auto-pr'
          pr_allow_empty: true
          github_token: ${{ secrets.PAT }}
